rename AutoPowerDown.html AutoPowerDown.html
rename BltIsConnected.html BltIsConnected.html
rename BltUnpair.html BltUnpair.html
rename CheckDate.html CheckDate.html
rename CheckTime.html CheckTime.html
rename ComClose.html ComClose.html
rename ComOpen.html ComOpen.html
rename CoreLeft.html CoreLeft.html
rename delay.html Delay.html
rename DownPressed.html DownPressed.html
rename EndTimer.html EndTimer.html
rename GetCom.html GetCom.html
rename getcom2.html GetCom2.html
rename GetCTS.html GetCTS.html
rename GetDate.html GetDate.html
rename getdatetime.html GetDateTime.html
rename GetDSR.html GetDSR.html
rename GetOsVersion.html GetOSVersion.html
rename GetTerminalID.html GetTerminalID.html
rename gettime.html GetTime.html
rename goodreadled.html GoodReadLed.html
rename idle.html Idle.html
rename isBuzzerOn.html IsBuzzerOn.html
rename ischarging.html IsCharging.html
rename osecomm.html OseComm.html
rename powereddown.html PoweredDown.html
rename putbuffer.html PutBuffer.html
rename PutCom.html PutCom.html
rename putcom2.html PutCom2.html
rename putnstring.html PutnString.html
rename putstring.html PutString.html
rename readbarcode.html ReadBarcode.html
rename resetkey.html ResetKey.html
rename resetreceive.html ResetReceive.html
rename scanneroff.html ScannerOff.html
rename scannerpower.html ScannerPower.html
rename setdate.html SetDate.html
rename setdatetime.html SetDateTime.html
rename SetDTR.html SetDTR.html
rename SetRTS.html SetRTS.html
rename setterminalid.html SetTerminalID.html
rename settime.html SetTime.html
rename sound.html Sound.html
rename starttimer.html StartTimer.html
rename systemsetting.html SystemSetting.html
rename timervalue.html TimerValue.html
rename triggerpressed.html TriggerPressed.html
rename vibrate.html Vibrate.html